// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class QaAutotestingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    driver.get("https://qauto2.forstudy.space/");
    driver.manage().window().setSize(new Dimension(884, 763));
    driver.findElement(By.cssSelector(".btn-outline-white")).click();
    driver.findElement(By.id("signinEmail")).sendKeys("Maksvel01@ukr.net");
    driver.findElement(By.id("signinPassword")).sendKeys("Maks1996");
    driver.findElement(By.cssSelector(".btn-primary:nth-child(2)")).click();
  }
  @Test
  public void createusers() {
    driver.get("https://qauto2.forstudy.space/panel/garage");
    driver.manage().window().setSize(new Dimension(884, 763));
    driver.findElement(By.id("userNavDropdown")).click();
    driver.findElement(By.linkText("Profile")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".d-block")).click();
    driver.findElement(By.id("editProfileLastName")).sendKeys("Lukash");
    driver.findElement(By.id("editProfileCountry")).click();
    driver.findElement(By.id("editProfileCountry")).sendKeys("Ukraine");
    driver.findElement(By.id("editProfileDateBirth")).click();
    driver.findElement(By.id("editProfileDateBirth")).sendKeys("16.01.1996");
    driver.findElement(By.cssSelector(".btn-primary:nth-child(1)")).click();
  }
  @Test
  public void addcar() {
    driver.get("https://qauto2.forstudy.space/panel/garage");
    driver.manage().window().setSize(new Dimension(884, 763));
    driver.findElement(By.cssSelector(".btn-primary")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("addCarMileage")).click();
    driver.findElement(By.id("addCarMileage")).sendKeys("100");
    driver.findElement(By.cssSelector(".modal-footer > .btn-primary")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".modal-footer > .btn-primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
  @Test
  public void expenses() {
    driver.get("https://qauto2.forstudy.space/panel/garage");
    driver.manage().window().setSize(new Dimension(884, 763));
    driver.findElement(By.id("addExpenseMileage")).sendKeys("111");
    driver.findElement(By.id("addExpenseLiters")).click();
    driver.findElement(By.id("addExpenseTotalCost")).click();
    driver.findElement(By.id("addExpenseTotalCost")).sendKeys("334");
    driver.findElement(By.cssSelector(".modal-footer > .btn-primary")).click();
  }
  @Test
  public void delete() {
    driver.get("https://qauto2.forstudy.space/panel/garage");
    driver.manage().window().setSize(new Dimension(884, 763));
    driver.findElement(By.cssSelector(".car-item:nth-child(2) .car-heading .icon")).click();
    driver.findElement(By.cssSelector(".btn-outline-danger")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-outline-danger"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".btn-danger")).click();
  }
}
